### ISSUE TITLE
support for Rademacher Dimmer (deviceID: 35140462)

### ISSUE THREAD

**Issue by ReismannRS** [bombadiltom/homebridge-rademacher-homepilot#32]
Hi,
i´m kind of new to gitHub. I have updated my index.js to include the dimmer (deviceID: 35140462) in homebridge.

the dimmer is showing up in homebridge after this and is also showing the correct light level. But it is not possible to set a light level within homebridge for this device. Is there something else that need to be updated maybe within the RademacherDimmerAccessory.js file?

I have not much experience in coding. So I am not able to do this on my own. Is there somone who can help?

**Comment by bombadiltom** [comment]
RademacherDimmerAccessory.js is not updated to new request structure yet

**Comment by bombadiltom** [comment]
Please provide http://\<homepilot-ip/>/v4/devices/\<did\>

**Comment by bombadiltom** [comment]
and maybe test the current master branch? should be working, but not show the correct brightness

**Comment by ReismannRS** [comment]
```
{ 
   "response":"get_device",
   "device":{ 
      "description":"Deckenlicht Wohnzimmer 2",
      "deviceGroup":4,
      "did":1010019,
      "hasErrors":0,
      "iconSetInverted":0,
      "iconSet":{ 
         "k":"iconset21"
      },
      "messages":[ 

      ],
      "name":"Licht Decke Wohnzimmer 2",
      "properties":{ 
         "closingContact":3,
         "dawn":3,
         "dusk":3,
         "motion":3,
         "rain":3,
         "smartphone":3,
         "smoke":3,
         "sun":3,
         "temperature":3,
         "time":3,
         "trigger":3,
         "warning":3,
         "wind":3
      },
      "statusValid":true,
      "statusesMap":{ 
         "Manuellbetrieb":0,
         "Position":0
      },
      "visible":true,
      "deviceNumber":"35140462",
      "uid":"4aXXXX_1",
      "voiceControlledBy":"Alexa",
      "sceneConfig":[ 
         "DIRECT_FUNCTION_CMD",
         "TURN_ON_CMD",
         "TURN_OFF_CMD",
         "GOTO_POS_CMD",
         "AUTO_MODE_CFG"
      ]
   }
}
```

**Comment by ReismannRS** [comment]
I tested the latest master but it´s still not working correct. device status and light level is updating within the home app but I am not able to set the light level or turn on/off the light within the home app or the homebridge Webinterface.

**Comment by bombadiltom** [comment]
please try again, if it does not work please provide logs

**Comment by ReismannRS** [comment]
Still does not work. Homebridge is restarting frequently with these changes

`[2019-10-12 4:51:59 PM] [RademacherHomePilot] Deckenlicht Wohnzimmer 2  [1010019] - dimmer changed=true
[2019-10-12 4:51:59 PM] TypeError: Cannot read property 'did' of undefined
    at RademacherDimmerAccessory.setStatus (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherDimmerAccessory.js:57:53)
    at Characteristic.emit (events.js:198:13)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at RademacherDimmerAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherDimmerAccessory.js:101:59)
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherDimmerAccessory.js:41:9
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:34:17
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1161:10)`

Let me know what else you need.

**Comment by bombadiltom** [comment]
Please try again

**Comment by ReismannRS** [comment]
It´s working! Thanks a lot for your great and fast support!
